GROUND_TRUTH = {   '1': {   'crowns': [   [0, 0, 0, 0, 0],
                           [0, 0, 0, 1, 0],
                           [0, 1, 0, 0, 0],
                           [0, 2, 0, 2, 1],
                           [0, 1, 0, 1, 0]],
             'terrain': [   ['Grass', 'Lake', 'Forest', 'Forest', 'Forest'],
                            ['Grass', 'Forest', 'Forest', 'Forest', 'Grass'],
                            ['Grass', 'Swamp', 'Home', 'Forest', 'Grass'],
                            ['Grass', 'Swamp', 'Lake', 'Grass', 'Grass'],
                            ['Forest', 'Lake', 'Lake', 'Grass', 'Field']]},
    '10': {   'crowns': [   [1, 0, 2, 2, 0],
                            [0, 1, 0, 0, 0],
                            [0, 0, 0, 2, 0],
                            [0, 1, 0, 0, 0],
                            [0, 1, 0, 1, 0]],
              'terrain': [   ['Field', 'Mine', 'Mine', 'Mine', 'Empty'],
                             ['Lake', 'Forest', 'Swamp', 'Swamp', 'Empty'],
                             ['Lake', 'Lake', 'Home', 'Swamp', 'Field'],
                             ['Lake', 'Lake', 'Forest', 'Field', 'Field'],
                             ['Lake', 'Lake', 'Forest', 'Forest', 'Forest']]},
    '11': {   'crowns': [   [0, 1, 0, 0, 0],
                            [1, 0, 1, 0, 0],
                            [1, 0, 0, 1, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Home'],
                             ['Lake', 'Grass', 'Grass', 'Forest', 'Forest'],
                             ['Empty', 'Empty', 'Grass', 'Forest', 'Forest']]},
    '12': {   'crowns': [   [0, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [0, 0, 2, 0, 0],
                            [0, 2, 0, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Field', 'Field', 'Grass', 'Grass', 'Empty'],
                             ['Forest', 'Lake', 'Lake', 'Lake', 'Empty'],
                             ['Grass', 'Grass', 'Grass', 'Forest', 'Lake'],
                             ['Grass', 'Swamp', 'Grass', 'Field', 'Lake'],
                             ['Swamp', 'Swamp', 'Home', 'Field', 'Lake']]},
    '13': {   'crowns': [   [0, 2, 0, 1, 0],
                            [0, 1, 0, 1, 1],
                            [0, 0, 2, 0, 0],
                            [0, 1, 0, 0, 0],
                            [1, 0, 1, 0, 0]],
              'terrain': [   ['Empty', 'Mine', 'Field', 'Field', 'Grass'],
                             ['Field', 'Grass', 'Lake', 'Field', 'Forest'],
                             ['Empty', 'Grass', 'Grass', 'Field', 'Field'],
                             ['Field', 'Swamp', 'Field', 'Field', 'Home'],
                             ['Swamp', 'Swamp', 'Field', 'Field', 'Lake']]},
    '14': {   'crowns': [   [1, 0, 2, 2, 0],
                            [0, 1, 0, 0, 0],
                            [0, 0, 0, 2, 0],
                            [0, 1, 0, 0, 0],
                            [0, 1, 0, 1, 0]],
              'terrain': [   ['Field', 'Mine', 'Mine', 'Mine', 'Empty'],
                             ['Lake', 'Forest', 'Swamp', 'Swamp', 'Empty'],
                             ['Lake', 'Lake', 'Home', 'Swamp', 'Field'],
                             ['Lake', 'Lake', 'Forest', 'Field', 'Field'],
                             ['Lake', 'Lake', 'Forest', 'Forest', 'Forest']]},
    '15': {   'crowns': [   [0, 1, 0, 0, 0],
                            [1, 0, 1, 0, 0],
                            [1, 0, 0, 1, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Home'],
                             ['Lake', 'Grass', 'Grass', 'Forest', 'Forest'],
                             ['Empty', 'Empty', 'Grass', 'Forest', 'Forest']]},
    '16': {   'crowns': [   [0, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [0, 0, 2, 0, 0],
                            [0, 2, 0, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Field', 'Field', 'Grass', 'Grass', 'Empty'],
                             ['Forest', 'Lake', 'Lake', 'Lake', 'Empty'],
                             ['Grass', 'Grass', 'Grass', 'Forest', 'Lake'],
                             ['Grass', 'Swamp', 'Grass', 'Field', 'Lake'],
                             ['Swamp', 'Swamp', 'Home', 'Field', 'Lake']]},
    '17': {   'crowns': [   [0, 0, 2, 0, 0],
                            [0, 0, 0, 0, 0],
                            [2, 0, 0, 0, 1],
                            [1, 1, 0, 1, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Swamp', 'Grass', 'Swamp', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Swamp', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Home', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Lake', 'Lake', 'Forest'],
                             ['Field', 'Grass', 'Lake', 'Lake', 'Lake']]},
    '18': {   'crowns': [   [0, 1, 0, 0, 0],
                            [0, 0, 1, 0, 1],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Grass', 'Forest', 'Field', 'Field', 'Lake'],
                             ['Empty', 'Forest', 'Forest', 'Field', 'Field'],
                             ['Empty', 'Forest', 'Home', 'Field', 'Field'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Lake', 'Forest', 'Forest', 'Forest']]},
    '19': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [2, 0, 0, 0, 0],
                            [2, 3, 0, 1, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Field', 'Grass', 'Forest', 'Grass', 'Lake'],
                             ['Field', 'Grass', 'Grass', 'Grass', 'Field'],
                             ['Mine', 'Swamp', 'Home', 'Forest', 'Field'],
                             ['Mine', 'Mine', 'Field', 'Forest', 'Swamp'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '2': {   'crowns': [   [0, 0, 0, 2, 0],
                           [1, 1, 0, 0, 0],
                           [2, 0, 0, 0, 0],
                           [2, 3, 0, 0, 1],
                           [0, 0, 0, 0, 0]],
             'terrain': [   ['Field', 'Swamp', 'Field', 'Mine', 'Swamp'],
                            ['Mine', 'Swamp', 'Field', 'Field', 'Forest'],
                            ['Mine', 'Swamp', 'Home', 'Field', 'Field'],
                            ['Mine', 'Mine', 'Grass', 'Grass', 'Grass'],
                            ['Field', 'Field', 'Swamp', 'Swamp', 'Grass']]},
    '20': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 0, 1],
                            [2, 0, 0, 0, 1],
                            [1, 0, 0, 2, 1],
                            [0, 1, 0, 0, 0]],
              'terrain': [   ['Lake', 'Lake', 'Lake', 'Lake', 'Lake'],
                             ['Forest', 'Swamp', 'Grass', 'Forest', 'Lake'],
                             ['Mine', 'Swamp', 'Home', 'Forest', 'Lake'],
                             ['Mine', 'Mine', 'Grass', 'Grass', 'Lake'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '21': {   'crowns': [   [0, 0, 2, 0, 0],
                            [0, 0, 0, 0, 0],
                            [2, 0, 0, 0, 1],
                            [1, 1, 0, 1, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Swamp', 'Grass', 'Swamp', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Swamp', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Home', 'Field', 'Forest'],
                             ['Swamp', 'Grass', 'Lake', 'Lake', 'Forest'],
                             ['Field', 'Grass', 'Lake', 'Lake', 'Lake']]},
    '22': {   'crowns': [   [0, 1, 0, 0, 0],
                            [0, 0, 1, 0, 1],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Grass', 'Forest', 'Field', 'Field', 'Lake'],
                             ['Empty', 'Forest', 'Forest', 'Field', 'Field'],
                             ['Empty', 'Forest', 'Home', 'Field', 'Field'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Lake', 'Forest', 'Forest', 'Forest']]},
    '23': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [2, 0, 0, 0, 0],
                            [2, 3, 0, 1, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Field', 'Grass', 'Forest', 'Grass', 'Lake'],
                             ['Field', 'Grass', 'Grass', 'Grass', 'Field'],
                             ['Mine', 'Swamp', 'Home', 'Forest', 'Field'],
                             ['Mine', 'Mine', 'Field', 'Forest', 'Swamp'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '24': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 0, 1],
                            [2, 0, 0, 0, 1],
                            [1, 0, 0, 2, 1],
                            [0, 1, 0, 0, 0]],
              'terrain': [   ['Lake', 'Lake', 'Lake', 'Lake', 'Lake'],
                             ['Forest', 'Swamp', 'Grass', 'Forest', 'Lake'],
                             ['Mine', 'Swamp', 'Home', 'Forest', 'Lake'],
                             ['Mine', 'Mine', 'Grass', 'Grass', 'Lake'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '25': {   'crowns': [   [0, 0, 1, 1, 0],
                            [0, 0, 0, 0, 1],
                            [0, 1, 0, 0, 0],
                            [1, 0, 0, 2, 0],
                            [0, 1, 2, 0, 1]],
              'terrain': [   ['Empty', 'Lake', 'Lake', 'Lake', 'Field'],
                             ['Empty', 'Forest', 'Forest', 'Lake', 'Field'],
                             ['Lake', 'Forest', 'Home', 'Lake', 'Field'],
                             ['Lake', 'Forest', 'Swamp', 'Mine', 'Field'],
                             ['Grass', 'Forest', 'Mine', 'Mine', 'Field']]},
    '26': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 1],
                            [0, 0, 1, 0, 1],
                            [1, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Lake'],
                             ['Forest', 'Field', 'Forest', 'Forest', 'Lake'],
                             ['Mine', 'Field', 'Home', 'Forest', 'Lake'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Lake'],
                             ['Lake', 'Lake', 'Lake', 'Lake', 'Lake']]},
    '27': {   'crowns': [   [0, 0, 0, 0, 0],
                            [0, 1, 2, 0, 0],
                            [0, 2, 0, 0, 1],
                            [1, 0, 0, 1, 0],
                            [0, 0, 1, 0, 0]],
              'terrain': [   ['Grass', 'Grass', 'Field', 'Field', 'Field'],
                             ['Lake', 'Grass', 'Grass', 'Field', 'Forest'],
                             ['Lake', 'Grass', 'Home', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Field', 'Field', 'Forest'],
                             ['Field', 'Grass', 'Forest', 'Forest', 'Forest']]},
    '28': {   'crowns': [   [2, 3, 0, 1, 0],
                            [0, 2, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [2, 1, 0, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Mine', 'Field', 'Field', 'Swamp'],
                             ['Swamp', 'Swamp', 'Grass', 'Grass', 'Forest'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Home'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Grass'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '29': {   'crowns': [   [0, 1, 0, 0, 1],
                            [1, 0, 0, 2, 0],
                            [1, 0, 0, 0, 2],
                            [0, 0, 1, 0, 1],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Field', 'Field', 'Field', 'Field', 'Field'],
                             ['Lake', 'Lake', 'Lake', 'Mine', 'Mine'],
                             ['Lake', 'Forest', 'Home', 'Swamp', 'Mine'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Empty', 'Empty', 'Lake', 'Lake', 'Grass']]},
    '3': {   'crowns': [   [2, 1, 0, 0, 0],
                           [0, 0, 1, 0, 0],
                           [0, 1, 0, 0, 1],
                           [0, 1, 0, 1, 0],
                           [0, 0, 1, 0, 1]],
             'terrain': [   ['Swamp', 'Field', 'Forest', 'Forest', 'Forest'],
                            ['Field', 'Field', 'Forest', 'Forest', 'Forest'],
                            ['Mine', 'Field', 'Home', 'Forest', 'Lake'],
                            ['Field', 'Forest', 'Forest', 'Forest', 'Lake'],
                            ['Lake', 'Lake', 'Lake', 'Forest', 'Lake']]},
    '30': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 1],
                            [0, 0, 1, 0, 1],
                            [1, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Lake'],
                             ['Forest', 'Field', 'Forest', 'Forest', 'Lake'],
                             ['Mine', 'Field', 'Home', 'Forest', 'Lake'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Lake'],
                             ['Lake', 'Lake', 'Lake', 'Lake', 'Lake']]},
    '31': {   'crowns': [   [0, 0, 0, 0, 0],
                            [0, 1, 2, 0, 0],
                            [0, 2, 0, 0, 1],
                            [1, 0, 0, 1, 0],
                            [0, 0, 1, 0, 0]],
              'terrain': [   ['Grass', 'Grass', 'Field', 'Field', 'Field'],
                             ['Lake', 'Grass', 'Grass', 'Field', 'Forest'],
                             ['Lake', 'Grass', 'Home', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Field', 'Field', 'Forest'],
                             ['Field', 'Grass', 'Forest', 'Forest', 'Forest']]},
    '32': {   'crowns': [   [2, 3, 0, 1, 0],
                            [0, 2, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [2, 1, 0, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Mine', 'Field', 'Field', 'Swamp'],
                             ['Swamp', 'Swamp', 'Grass', 'Grass', 'Forest'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Home'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Grass'],
                             ['Field', 'Field', 'Field', 'Field', 'Field']]},
    '33': {   'crowns': [   [2, 0, 1, 0, 1],
                            [0, 1, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0]],
              'terrain': [   ['Grass', 'Field', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Swamp', 'Field', 'Forest'],
                             ['Lake', 'Field', 'Home', 'Forest', 'Forest'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Empty'],
                             ['Lake', 'Forest', 'Field', 'Field', 'Empty']]},
    '34': {   'crowns': [   [0, 0, 0, 0, 0],
                            [2, 0, 0, 0, 1],
                            [0, 2, 0, 0, 0],
                            [2, 0, 0, 1, 1],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Swamp', 'Swamp', 'Home', 'Grass', 'Grass'],
                             ['Swamp', 'Field', 'Field', 'Grass', 'Grass'],
                             ['Swamp', 'Mine', 'Field', 'Field', 'Field'],
                             ['Swamp', 'Grass', 'Field', 'Forest', 'Field'],
                             ['Forest', 'Grass', 'Field', 'Mine', 'Lake']]},
    '35': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [3, 2, 0, 2, 0]],
              'terrain': [   ['Swamp', 'Field', 'Forest', 'Forest', 'Forest'],
                             ['Swamp', 'Forest', 'Forest', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Home', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Field', 'Lake', 'Lake'],
                             ['Mine', 'Mine', 'Mine', 'Mine', 'Swamp']]},
    '36': {   'crowns': [   [0, 1, 0, 0, 1],
                            [1, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 1, 1, 0, 0],
                            [0, 0, 0, 2, 0]],
              'terrain': [   ['Field', 'Forest', 'Forest', 'Forest', 'Swamp'],
                             ['Field', 'Field', 'Forest', 'Home', 'Grass'],
                             ['Grass', 'Field', 'Forest', 'Forest', 'Grass'],
                             ['Lake', 'Forest', 'Forest', 'Grass', 'Grass'],
                             ['Lake', 'Field', 'Lake', 'Grass', 'Lake']]},
    '37': {   'crowns': [   [2, 0, 1, 0, 1],
                            [0, 1, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0]],
              'terrain': [   ['Grass', 'Field', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Swamp', 'Field', 'Forest'],
                             ['Lake', 'Field', 'Home', 'Forest', 'Forest'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Empty'],
                             ['Lake', 'Forest', 'Field', 'Field', 'Empty']]},
    '38': {   'crowns': [   [0, 0, 0, 0, 0],
                            [2, 0, 0, 0, 1],
                            [0, 2, 0, 0, 0],
                            [2, 0, 0, 1, 1],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Swamp', 'Swamp', 'Home', 'Grass', 'Grass'],
                             ['Swamp', 'Field', 'Field', 'Grass', 'Grass'],
                             ['Swamp', 'Mine', 'Field', 'Field', 'Field'],
                             ['Swamp', 'Grass', 'Field', 'Forest', 'Field'],
                             ['Forest', 'Grass', 'Field', 'Mine', 'Lake']]},
    '39': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [3, 2, 0, 2, 0]],
              'terrain': [   ['Swamp', 'Field', 'Forest', 'Forest', 'Forest'],
                             ['Swamp', 'Forest', 'Forest', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Home', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Field', 'Lake', 'Lake'],
                             ['Mine', 'Mine', 'Mine', 'Mine', 'Swamp']]},
    '4': {   'crowns': [   [1, 0, 1, 0, 0],
                           [0, 1, 2, 0, 0],
                           [0, 0, 0, 0, 0],
                           [1, 0, 0, 1, 1],
                           [0, 0, 0, 0, 0]],
             'terrain': [   ['Lake', 'Field', 'Field', 'Swamp', 'Field'],
                            ['Lake', 'Field', 'Grass', 'Grass', 'Field'],
                            ['Lake', 'Field', 'Field', 'Field', 'Field'],
                            ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                            ['Lake', 'Lake', 'Home', 'Lake', 'Lake']]},
    '40': {   'crowns': [   [0, 1, 0, 0, 1],
                            [1, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 1, 1, 0, 0],
                            [0, 0, 0, 2, 0]],
              'terrain': [   ['Field', 'Forest', 'Forest', 'Forest', 'Swamp'],
                             ['Field', 'Field', 'Forest', 'Home', 'Grass'],
                             ['Grass', 'Field', 'Forest', 'Forest', 'Grass'],
                             ['Lake', 'Forest', 'Forest', 'Grass', 'Grass'],
                             ['Lake', 'Field', 'Lake', 'Grass', 'Lake']]},
    '41': {   'crowns': [   [0, 0, 1, 0, 1],
                            [2, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [2, 0, 0, 1, 0],
                            [3, 0, 0, 0, 0]],
              'terrain': [   ['Field', 'Swamp', 'Field', 'Forest', 'Lake'],
                             ['Grass', 'Grass', 'Field', 'Field', 'Lake'],
                             ['Forest', 'Lake', 'Lake', 'Lake', 'Lake'],
                             ['Mine', 'Swamp', 'Field', 'Forest', 'Lake'],
                             ['Mine', 'Field', 'Field', 'Forest', 'Home']]},
    '42': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 0, 0],
                            [0, 1, 0, 1, 2],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Field', 'Lake', 'Lake', 'Forest', 'Forest'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Forest'],
                             ['Field', 'Lake', 'Forest', 'Forest', 'Swamp'],
                             ['Field', 'Lake', 'Lake', 'Forest', 'Mine'],
                             ['Field', 'Field', 'Field', 'Forest', 'Home']]},
    '43': {   'crowns': [   [1, 0, 0, 1, 1],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [2, 0, 1, 0, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Field', 'Field'],
                             ['Grass', 'Grass', 'Grass', 'Field', 'Mine'],
                             ['Lake', 'Grass', 'Home', 'Field', 'Mine'],
                             ['Swamp', 'Grass', 'Grass', 'Field', 'Grass'],
                             ['Lake', 'Grass', 'Grass', 'Grass', 'Grass']]},
    '44': {   'crowns': [   [0, 0, 1, 0, 1],
                            [2, 0, 0, 0, 0],
                            [0, 1, 0, 0, 0],
                            [2, 0, 0, 1, 0],
                            [3, 0, 0, 0, 0]],
              'terrain': [   ['Field', 'Swamp', 'Field', 'Forest', 'Lake'],
                             ['Grass', 'Grass', 'Field', 'Field', 'Lake'],
                             ['Forest', 'Lake', 'Lake', 'Lake', 'Lake'],
                             ['Mine', 'Swamp', 'Field', 'Forest', 'Lake'],
                             ['Mine', 'Field', 'Field', 'Forest', 'Home']]},
    '45': {   'crowns': [   [0, 0, 1, 0, 0],
                            [0, 0, 0, 2, 1],
                            [0, 0, 2, 0, 0],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 1, 0]],
              'terrain': [   ['Forest', 'Field', 'Swamp', 'Field', 'Grass'],
                             ['Forest', 'Field', 'Swamp', 'Swamp', 'Swamp'],
                             ['Home', 'Field', 'Mine', 'Swamp', 'Swamp'],
                             ['Forest', 'Field', 'Field', 'Lake', 'Lake'],
                             ['Forest', 'Forest', 'Forest', 'Lake', 'Lake']]},
    '46': {   'crowns': [   [1, 0, 0, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 0, 0],
                            [0, 1, 0, 1, 2],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Field', 'Lake', 'Lake', 'Forest', 'Forest'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Forest'],
                             ['Field', 'Lake', 'Forest', 'Forest', 'Swamp'],
                             ['Field', 'Lake', 'Lake', 'Forest', 'Mine'],
                             ['Field', 'Field', 'Field', 'Forest', 'Home']]},
    '47': {   'crowns': [   [1, 0, 0, 1, 1],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [2, 0, 1, 0, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Field', 'Field'],
                             ['Grass', 'Grass', 'Grass', 'Field', 'Mine'],
                             ['Lake', 'Grass', 'Home', 'Field', 'Mine'],
                             ['Swamp', 'Grass', 'Grass', 'Field', 'Grass'],
                             ['Lake', 'Grass', 'Grass', 'Grass', 'Grass']]},
    '48': {   'crowns': [   [0, 2, 0, 0, 0],
                            [1, 0, 0, 0, 1],
                            [1, 0, 0, 0, 1],
                            [0, 1, 2, 0, 0],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Lake', 'Swamp', 'Field', 'Forest', 'Forest'],
                             ['Field', 'Field', 'Field', 'Field', 'Forest'],
                             ['Field', 'Field', 'Home', 'Field', 'Forest'],
                             ['Swamp', 'Mine', 'Mine', 'Field', 'Field'],
                             ['Swamp', 'Swamp', 'Swamp', 'Swamp', 'Swamp']]},
    '49': {   'crowns': [   [0, 0, 1, 0, 0],
                            [0, 0, 3, 0, 0],
                            [1, 0, 0, 0, 0],
                            [2, 0, 0, 1, 1],
                            [0, 0, 1, 0, 0]],
              'terrain': [   ['Field', 'Lake', 'Lake', 'Forest', 'Forest'],
                             ['Field', 'Lake', 'Mine', 'Field', 'Lake'],
                             ['Swamp', 'Grass', 'Home', 'Lake', 'Lake'],
                             ['Grass', 'Grass', 'Forest', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Forest']]},
    '5': {   'crowns': [   [0, 0, 0, 0, 0],
                           [0, 0, 0, 1, 0],
                           [0, 1, 0, 0, 0],
                           [0, 2, 0, 2, 1],
                           [0, 1, 0, 1, 0]],
             'terrain': [   ['Grass', 'Lake', 'Forest', 'Forest', 'Forest'],
                            ['Grass', 'Forest', 'Forest', 'Forest', 'Grass'],
                            ['Grass', 'Swamp', 'Home', 'Forest', 'Grass'],
                            ['Grass', 'Swamp', 'Lake', 'Grass', 'Grass'],
                            ['Forest', 'Lake', 'Lake', 'Grass', 'Field']]},
    '50': {   'crowns': [   [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 2]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Field', 'Grass'],
                             ['Forest', 'Forest', 'Forest', 'Field', 'Grass'],
                             ['Forest', 'Lake', 'Home', 'Field', 'Grass'],
                             ['Lake', 'Lake', 'Field', 'Field', 'Mine'],
                             ['Lake', 'Lake', 'Lake', 'Swamp', 'Mine']]},
    '51': {   'crowns': [   [1, 0, 1, 1, 0],
                            [0, 1, 0, 2, 0],
                            [0, 0, 0, 0, 1],
                            [0, 2, 0, 0, 0],
                            [1, 0, 2, 0, 0]],
              'terrain': [   ['Grass', 'Grass', 'Lake', 'Lake', 'Field'],
                             ['Lake', 'Forest', 'Forest', 'Mine', 'Field'],
                             ['Forest', 'Forest', 'Home', 'Grass', 'Field'],
                             ['Field', 'Swamp', 'Lake', 'Grass', 'Field'],
                             ['Grass', 'Grass', 'Grass', 'Grass', 'Field']]},
    '52': {   'crowns': [   [0, 2, 0, 0, 0],
                            [1, 0, 0, 0, 1],
                            [1, 1, 0, 0, 1],
                            [0, 1, 2, 0, 0],
                            [0, 0, 0, 1, 0]],
              'terrain': [   ['Lake', 'Swamp', 'Field', 'Forest', 'Forest'],
                             ['Field', 'Field', 'Field', 'Field', 'Forest'],
                             ['Field', 'Field', 'Home', 'Field', 'Forest'],
                             ['Swamp', 'Mine', 'Mine', 'Field', 'Field'],
                             ['Swamp', 'Swamp', 'Swamp', 'Swamp', 'Swamp']]},
    '53': {   'crowns': [   [0, 0, 1, 0, 0],
                            [0, 0, 0, 0, 0],
                            [1, 0, 0, 0, 0],
                            [2, 0, 0, 1, 1],
                            [0, 0, 1, 0, 0]],
              'terrain': [   ['Field', 'Lake', 'Lake', 'Forest', 'Forest'],
                             ['Field', 'Forest', 'Mine', 'Field', 'Lake'],
                             ['Swamp', 'Grass', 'Home', 'Lake', 'Lake'],
                             ['Grass', 'Grass', 'Forest', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Forest', 'Forest', 'Forest']]},
    '54': {   'crowns': [   [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 0],
                            [0, 1, 0, 1, 0],
                            [0, 0, 0, 0, 2]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Field', 'Grass'],
                             ['Forest', 'Forest', 'Forest', 'Field', 'Grass'],
                             ['Forest', 'Lake', 'Home', 'Field', 'Grass'],
                             ['Lake', 'Lake', 'Field', 'Field', 'Mine'],
                             ['Lake', 'Lake', 'Lake', 'Swamp', 'Mine']]},
    '55': {   'crowns': [   [1, 0, 1, 1, 0],
                            [0, 1, 0, 2, 0],
                            [0, 0, 0, 0, 1],
                            [0, 2, 0, 0, 0],
                            [1, 0, 2, 1, 0]],
              'terrain': [   ['Grass', 'Grass', 'Lake', 'Lake', 'Field'],
                             ['Lake', 'Forest', 'Forest', 'Mine', 'Field'],
                             ['Forest', 'Forest', 'Home', 'Grass', 'Field'],
                             ['Field', 'Swamp', 'Lake', 'Grass', 'Field'],
                             ['Grass', 'Grass', 'Grass', 'Grass', 'Field']]},
    '56': {   'crowns': [   [2, 0, 1, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 0, 2, 0, 1],
                            [2, 0, 0, 1, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Forest', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Forest', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Mine', 'Lake', 'Lake'],
                             ['Swamp', 'Swamp', 'Swamp', 'Forest', 'Forest'],
                             ['Swamp', 'Swamp', 'Home', 'Field', 'Forest']]},
    '57': {   'crowns': [   [0, 1, 0, 0, 0],
                            [0, 0, 2, 0, 0],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [0, 2, 2, 0, 0]],
              'terrain': [   ['Grass', 'Forest', 'Grass', 'Grass', 'Lake'],
                             ['Grass', 'Forest', 'Grass', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Grass', 'Field', 'Home'],
                             ['Grass', 'Swamp', 'Grass', 'Field', 'Field'],
                             ['Grass', 'Swamp', 'Grass', 'Lake', 'Lake']]},
    '58': {   'crowns': [   [0, 0, 1, 0, 0],
                            [1, 2, 0, 0, 1],
                            [0, 1, 0, 0, 0],
                            [0, 0, 0, 0, 1],
                            [1, 1, 0, 0, 0]],
              'terrain': [   ['Field', 'Swamp', 'Swamp', 'Field', 'Home'],
                             ['Mine', 'Mine', 'Field', 'Field', 'Forest'],
                             ['Mine', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Field', 'Forest', 'Forest']]},
    '59': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 1, 0, 1],
                            [0, 0, 0, 1, 0],
                            [0, 0, 1, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Field', 'Home', 'Field', 'Lake'],
                             ['Forest', 'Field', 'Lake', 'Field', 'Lake'],
                             ['Forest', 'Field', 'Field', 'Field', 'Lake'],
                             ['Forest', 'Forest', 'Field', 'Swamp', 'Lake'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Lake']]},
    '6': {   'crowns': [   [0, 0, 0, 2, 0],
                           [1, 1, 0, 0, 0],
                           [2, 0, 0, 0, 0],
                           [2, 3, 0, 0, 1],
                           [0, 0, 0, 0, 0]],
             'terrain': [   ['Field', 'Swamp', 'Field', 'Mine', 'Swamp'],
                            ['Mine', 'Swamp', 'Field', 'Field', 'Forest'],
                            ['Mine', 'Swamp', 'Home', 'Field', 'Field'],
                            ['Mine', 'Mine', 'Grass', 'Grass', 'Field'],
                            ['Field', 'Field', 'Swamp', 'Swamp', 'Grass']]},
    '60': {   'crowns': [   [2, 0, 1, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 0, 2, 0, 1],
                            [2, 0, 0, 1, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Forest', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Forest', 'Lake', 'Lake', 'Lake'],
                             ['Field', 'Field', 'Mine', 'Lake', 'Lake'],
                             ['Swamp', 'Swamp', 'Swamp', 'Forest', 'Forest'],
                             ['Swamp', 'Swamp', 'Home', 'Field', 'Forest']]},
    '61': {   'crowns': [   [0, 1, 0, 0, 0],
                            [0, 0, 2, 0, 0],
                            [0, 0, 0, 1, 0],
                            [0, 1, 0, 0, 1],
                            [0, 2, 2, 0, 0]],
              'terrain': [   ['Grass', 'Forest', 'Grass', 'Grass', 'Lake'],
                             ['Grass', 'Forest', 'Grass', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Grass', 'Field', 'Home'],
                             ['Grass', 'Swamp', 'Grass', 'Field', 'Field'],
                             ['Grass', 'Swamp', 'Grass', 'Lake', 'Lake']]},
    '62': {   'crowns': [   [0, 0, 1, 0, 0],
                            [1, 2, 0, 0, 1],
                            [0, 1, 0, 0, 0],
                            [0, 0, 0, 0, 1],
                            [1, 1, 0, 0, 0]],
              'terrain': [   ['Field', 'Swamp', 'Swamp', 'Field', 'Home'],
                             ['Mine', 'Mine', 'Field', 'Field', 'Forest'],
                             ['Mine', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Field', 'Field', 'Field', 'Forest'],
                             ['Grass', 'Grass', 'Field', 'Forest', 'Forest']]},
    '63': {   'crowns': [   [3, 0, 0, 0, 0],
                            [1, 0, 1, 0, 1],
                            [0, 0, 0, 1, 0],
                            [0, 0, 1, 0, 0],
                            [0, 0, 0, 0, 1]],
              'terrain': [   ['Mine', 'Field', 'Home', 'Field', 'Lake'],
                             ['Forest', 'Field', 'Lake', 'Field', 'Lake'],
                             ['Forest', 'Field', 'Field', 'Field', 'Lake'],
                             ['Forest', 'Forest', 'Field', 'Swamp', 'Lake'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Lake']]},
    '64': {   'crowns': [   [0, 1, 1, 1, 0],
                            [0, 0, 0, 0, 1],
                            [1, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Forest', 'Forest', 'Field'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Home']]},
    '65': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [0, 0, 2, 0, 0],
                            [0, 1, 1, 0, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Grass', 'Grass', 'Lake', 'Field', 'Swamp'],
                             ['Forest', 'Grass', 'Grass', 'Field', 'Field'],
                             ['Forest', 'Grass', 'Grass', 'Field', 'Home'],
                             ['Lake', 'Grass', 'Grass', 'Field', 'Field'],
                             ['Lake', 'Grass', 'Grass', 'Grass', 'Grass']]},
    '66': {   'crowns': [   [1, 0, 0, 0, 1],
                            [0, 1, 3, 2, 0],
                            [0, 2, 2, 2, 0],
                            [1, 0, 0, 1, 0],
                            [0, 0, 2, 0, 0]],
              'terrain': [   ['Field', 'Field', 'Field', 'Field', 'Field'],
                             ['Swamp', 'Mine', 'Mine', 'Mine', 'Mine'],
                             ['Swamp', 'Mine', 'Mine', 'Swamp', 'Field'],
                             ['Swamp', 'Field', 'Swamp', 'Swamp', 'Grass'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Home']]},
    '67': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [1, 0, 1, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 1]],
              'terrain': [   ['Lake', 'Lake', 'Lake', 'Lake', 'Home'],
                             ['Lake', 'Field', 'Lake', 'Lake', 'Lake'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Lake', 'Lake', 'Lake', 'Lake']]},
    '68': {   'crowns': [   [0, 1, 1, 1, 0],
                            [0, 0, 0, 0, 1],
                            [1, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Forest', 'Forest', 'Field'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Home']]},
    '69': {   'crowns': [   [1, 0, 0, 0, 1],
                            [0, 1, 3, 2, 0],
                            [0, 2, 2, 2, 0],
                            [1, 0, 0, 1, 0],
                            [0, 0, 2, 0, 0]],
              'terrain': [   ['Field', 'Field', 'Field', 'Field', 'Field'],
                             ['Swamp', 'Mine', 'Mine', 'Mine', 'Mine'],
                             ['Swamp', 'Mine', 'Mine', 'Swamp', 'Field'],
                             ['Swamp', 'Field', 'Swamp', 'Swamp', 'Grass'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Home']]},
    '7': {   'crowns': [   [2, 1, 0, 0, 0],
                           [0, 0, 0, 0, 0],
                           [0, 1, 0, 0, 1],
                           [0, 1, 0, 1, 0],
                           [0, 0, 1, 0, 1]],
             'terrain': [   ['Swamp', 'Field', 'Forest', 'Forest', 'Forest'],
                            ['Field', 'Field', 'Forest', 'Forest', 'Forest'],
                            ['Mine', 'Field', 'Home', 'Forest', 'Lake'],
                            ['Field', 'Forest', 'Forest', 'Forest', 'Lake'],
                            ['Lake', 'Lake', 'Lake', 'Forest', 'Lake']]},
    '70': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [1, 0, 1, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 1]],
              'terrain': [   ['Lake', 'Lake', 'Lake', 'Lake', 'Home'],
                             ['Lake', 'Field', 'Lake', 'Lake', 'Lake'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Lake', 'Lake', 'Lake', 'Lake']]},
    '71': {   'crowns': [   [0, 1, 1, 1, 0],
                            [0, 0, 0, 0, 1],
                            [1, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0],
                            [0, 0, 0, 0, 0]],
              'terrain': [   ['Forest', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Field', 'Field', 'Field'],
                             ['Forest', 'Field', 'Forest', 'Forest', 'Field'],
                             ['Forest', 'Forest', 'Forest', 'Forest', 'Home']]},
    '72': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [0, 0, 2, 0, 0],
                            [0, 1, 1, 0, 0],
                            [0, 2, 0, 0, 0]],
              'terrain': [   ['Grass', 'Grass', 'Lake', 'Field', 'Swamp'],
                             ['Forest', 'Grass', 'Grass', 'Field', 'Field'],
                             ['Forest', 'Grass', 'Grass', 'Field', 'Home'],
                             ['Lake', 'Grass', 'Grass', 'Field', 'Field'],
                             ['Lake', 'Grass', 'Grass', 'Grass', 'Grass']]},
    '73': {   'crowns': [   [1, 0, 0, 0, 1],
                            [0, 1, 3, 2, 0],
                            [0, 2, 2, 2, 0],
                            [1, 0, 0, 1, 0],
                            [0, 0, 2, 0, 0]],
              'terrain': [   ['Field', 'Field', 'Field', 'Field', 'Field'],
                             ['Swamp', 'Mine', 'Mine', 'Mine', 'Mine'],
                             ['Swamp', 'Mine', 'Mine', 'Swamp', 'Field'],
                             ['Swamp', 'Field', 'Swamp', 'Swamp', 'Grass'],
                             ['Swamp', 'Swamp', 'Swamp', 'Grass', 'Home']]},
    '74': {   'crowns': [   [0, 0, 0, 0, 0],
                            [1, 0, 0, 1, 0],
                            [1, 0, 1, 0, 0],
                            [0, 0, 1, 0, 0],
                            [0, 1, 0, 1, 1]],
              'terrain': [   ['Lake', 'Lake', 'Lake', 'Lake', 'Home'],
                             ['Lake', 'Field', 'Lake', 'Lake', 'Lake'],
                             ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                             ['Lake', 'Forest', 'Forest', 'Forest', 'Forest'],
                             ['Lake', 'Lake', 'Lake', 'Lake', 'Lake']]},
    '8': {   'crowns': [   [1, 0, 1, 0, 0],
                           [0, 1, 2, 0, 0],
                           [0, 0, 0, 0, 0],
                           [1, 0, 0, 1, 1],
                           [0, 0, 0, 0, 0]],
             'terrain': [   ['Lake', 'Field', 'Field', 'Swamp', 'Field'],
                            ['Lake', 'Field', 'Grass', 'Grass', 'Field'],
                            ['Lake', 'Field', 'Field', 'Field', 'Field'],
                            ['Lake', 'Field', 'Field', 'Forest', 'Forest'],
                            ['Lake', 'Lake', 'Home', 'Lake', 'Lake']]},
    '9': {   'crowns': [   [0, 2, 0, 1, 0],
                           [0, 1, 0, 1, 1],
                           [0, 0, 2, 0, 0],
                           [0, 1, 0, 0, 0],
                           [1, 0, 1, 0, 0]],
             'terrain': [   ['Empty', 'Mine', 'Field', 'Field', 'Grass'],
                            ['Field', 'Grass', 'Lake', 'Field', 'Forest'],
                            ['Empty', 'Grass', 'Grass', 'Field', 'Field'],
                            ['Field', 'Swamp', 'Field', 'Field', 'Home'],
                            ['Swamp', 'Swamp', 'Field', 'Field', 'Lake']]}}
